spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:backofficeDb
    #url: jdbc:h2:file:/Users/parkkyutae/Documents/sources/github/fastcampus-demo-01/record-example/sample1/backofficeDb
    driver-class-name: org.h2.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      format_sql: true
      hibernate:
        show-sql: true
    defer-datasource-initialization: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mustache:
    suffix: .html
  mail:
    host: smtp.gmail.com
    port: 587
    username: seonghyuk518@gmail.com
    password: ccskjofakmafjpxc
    properties:
      mail:
        smtp:
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace
  file:
    name: ./logs/spring-jpa.log




